### ISSUE TITLE
Job Interface

### ISSUE THREAD

**Issue by nixpulvis** [nixpulvis/oursh#4]
Today I've written a little bit of code that uses `fork`, `wait` and `execvp` directly. There's built in support for this kind of thing in `std::process`, however I'm not 100% sure which approach will be needed yet. We either need to beef up the command interface inside `mod job` or replace it with something that exists.

Key features to support:
- [x] Basic execution
- [ ] Argument control (`foo -b -bar --baz "more stuff"`)
- [ ] #27 Environment variable control (`FOO=bar env`)
- [ ] Working directory control (possible syntax `pwd @ /home`)
- [ ] #26 IO redirects (`[n]<`, `[n]>`, `[n]>|`, `[n]>>`, `[n]<<`, `[n]<<-`, `[n]<&`, `[n]>&`, `[n]<>`)
- [ ] #15 Subshells (`(date)`)
- [ ] #12 Piping (`|`, and possibly `|&` shorthand)
- [ ] #6 Background jobs (`&`, `wait`, etc)
- [ ] #24 Builtins (`exit`, `cd`, etc)
- [ ] #25, #27 Status interface (`$?`, `!`, `&&`, `||`)

**Comment by nixpulvis** [comment]
https://en.wikipedia.org/wiki/Job_control_(Unix)

**Comment by nixpulvis** [comment]
https://users.rust-lang.org/t/prevent-program-from-exiting-on-child-sigint/7685/13

**Comment by nixpulvis** [comment]
https://www.gnu.org/software/libc/manual/html_node/Data-Structures.html#Data-Structures
